<?php 

/**
 * @file
 * Basic monitoring isup module.
 * 
 * Two main functions:
 *   - provides block with url check form
 *   - provides isup/$url json request
 */

/**
 * Implements hook_menu().
 */
function isup_menu() {
  $items['isup'] = array(
    'title' => 'Is is up?',
    'description' => 'Check if website is up.',
    'access callback' => TRUE,
    'page callback' => 'isup_check',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    // 'file' => 'module_filter.admin.inc'
  );
  return $items;
}

function isup_check() {
	$url = arg(1);
	
	if ($url == NULL) {
		print 'null';
		exit;
	}

	$request = _isup_curl_request($url);

	$request_json = drupal_json_encode($request);
	
	print $request_json;
}

/*
 * Curl request to check for url
 */
function _isup_curl_request($url) {
	$ch = curl_init($url);

    $options = array(
        CURLOPT_NOBODY => true,
        CURLOPT_FOLLOWLOCATION => true,

    );
    curl_setopt_array($ch, $options);
    
    curl_exec($ch);
    $retcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($retcode == 200) {
        $return = array(
            'status' => TRUE,
            'retcode' => $retcode,
            'error' => '',
        );
        return $return;
    } else {
        $return = array(
            'status' => FALSE,
            'retcode' => $retcode,
            'error' => curl_error($ch),
        );
        return $return;
    }
}

function isup_check_form($form, &$form_state) {
	$form['url'] = array(
		'#type' => 'textfield',
		'#size' => 20,
		'#required' => TRUE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);

	return $form;
}

function isup_check_form_validate($form, &$form_state) {
	$url = $form_state['values']['url'];
	if ($url == NULL) {
		form_set_error('url empty', 'URL must not be empty.');
	}

}

function isup_check_form_submit($form, &$form_state) {
	$url = $form_state['values']['url'];
	$request = _isup_curl_request($url);

	if ($request['status']) {
		drupal_set_message('Your site is up.');
	}
	else {
		drupal_set_message('Your site is down.');
	}
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function isup_block_info() {
  $blocks['isup_check'] = array(
      'info' => t('Is Up Check'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function isup_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'isup_check':
      $block['content'] = drupal_get_form('isup_check_form');
      break;
  }
  return $block;
}